<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Teknik Informatika_fa fa-trash</name>
   <tag></tag>
   <elementGuidId>474e806c-abea-4521-a56f-9d8a7653d88d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='dt-basic-example']/tbody/tr[7]/td[5]/a/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;7 Teknik Informatika &quot;i] >> internal:role=link</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>1e025782-db50-4ce5-a0e3-06eee02559ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-trash</value>
      <webElementGuid>dde7c195-5b76-4103-81d5-a97929d11b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dt-basic-example&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[5]/a[@class=&quot;btn btn-danger waves-effect waves-themed&quot;]/i[@class=&quot;fa fa-trash&quot;]</value>
      <webElementGuid>0bb2ad84-89c0-4428-b079-8dbf977b0256</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dt-basic-example']/tbody/tr[7]/td[5]/a/i</value>
      <webElementGuid>31a84b32-5cb9-484f-88a1-24699b5ca6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[5]/a/i</value>
      <webElementGuid>3b43795c-7d78-495b-b4ee-0170fa4040b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
