<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Terbitkan</name>
   <tag></tag>
   <elementGuidId>97a996fd-e143-4dd9-a23d-3ffbb411a0f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-warning.mr-1.waves-effect.waves-themed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Terbitkan&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e9c9cd63-822b-4cc9-8c56-445163ed3e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/assessment/publish/1</value>
      <webElementGuid>e10c8387-e94d-4584-a66e-ff8bec83df88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-warning mr-1 waves-effect waves-themed</value>
      <webElementGuid>f8e24170-2ccb-4785-8e63-f63f46d3961c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                             Terbitkan
                        </value>
      <webElementGuid>cf01f6cf-1552-4443-aa23-d0f1d8088390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-1X3cb&quot;)/div[@class=&quot;panel-container show&quot;]/div[@class=&quot;panel-content&quot;]/div[@class=&quot;d-flex justify-content-end mt-3&quot;]/a[@class=&quot;btn btn-warning mr-1 waves-effect waves-themed&quot;]</value>
      <webElementGuid>73ba85b9-024a-4970-a1a9-59e97bccf646</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-1X3cb']/div[2]/div/div[2]/a</value>
      <webElementGuid>fe1af22d-def8-42bd-9a62-4e7c049abe1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[3]/following::a[1]</value>
      <webElementGuid>34b224fb-58d6-4c2c-955e-a075b5ef2cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hapus'])[2]/following::a[1]</value>
      <webElementGuid>ff4995b2-2bfa-46fe-880d-ef94e2dd9440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::a[2]</value>
      <webElementGuid>08c5d7c8-5050-48a7-b8fe-d1f063023520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Terbitkan']/parent::*</value>
      <webElementGuid>27328cde-55a5-4614-b5bc-07847fae5e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/assessment/publish/1']</value>
      <webElementGuid>50b2e581-c0ce-443e-9c2c-246bd7f48993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a</value>
      <webElementGuid>0b37c959-736e-4dc4-abe2-119b0262afa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/assessment/publish/1' and (text() = '
                             Terbitkan
                        ' or . = '
                             Terbitkan
                        ')]</value>
      <webElementGuid>8943586e-d300-4fe8-a041-48a0e78aa391</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
