<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Pilih Mata Kuliah</name>
   <tag></tag>
   <elementGuidId>4fe940d5-c26b-4fd5-8543-e2500b369e78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary.waves-effect.waves-themed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;+ Pilih Mata Kuliah&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>24a1e21a-5e34-49cb-bc45-b1035ab9986e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ffe5d520-54ad-401c-8e61-8143e8e98f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary waves-effect waves-themed</value>
      <webElementGuid>929ee4b2-83ad-4de9-bd85-5a0a2055594c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>4c6f0aa4-82eb-470d-8015-28d0e1b76750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#uploaddata</value>
      <webElementGuid>e3783d7e-4360-49ae-bd2c-687dfc70d2b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                 Pilih Mata Kuliah
                            </value>
      <webElementGuid>9201ff9f-2f04-42d0-acbf-c1c6e670a34c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-r0zRE&quot;)/div[@class=&quot;panel-hdr&quot;]/div[@class=&quot;d-flex justify-content-between align-items-center flex-wrap gap-2&quot;]/button[@class=&quot;btn btn-primary waves-effect waves-themed&quot;]</value>
      <webElementGuid>a32d79c9-1cd5-4cbc-8710-35b1d234afea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[2]</value>
      <webElementGuid>eced67ad-1947-42a2-a556-47395732a948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-r0zRE']/div/div/button</value>
      <webElementGuid>a0d8f994-98b7-44c9-95e0-8f3553f5e157</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Silakan lakukan penilaian'])[1]/following::button[1]</value>
      <webElementGuid>c996011b-1f6c-4c0c-94dc-1a6b5474c7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tambah Mata Kuliah Konversi'])[1]/preceding::button[1]</value>
      <webElementGuid>574f6141-a271-407e-9132-a338dc72e635</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nama Mata Kuliah'])[1]/preceding::button[2]</value>
      <webElementGuid>b2385e5b-a60a-4045-b4ae-aedda89311f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Pilih Mata Kuliah']/parent::*</value>
      <webElementGuid>8078421b-28d2-4968-8c65-7d98989e5312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/button</value>
      <webElementGuid>be7aea82-08e4-4dc5-bfcd-8729e4c77d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = '
                                 Pilih Mata Kuliah
                            ' or . = '
                                 Pilih Mata Kuliah
                            ')]</value>
      <webElementGuid>4e70df8f-132f-469b-b22c-1b08c466519f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
