<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Login</name>
   <tag></tag>
   <elementGuidId>0b2b86d7-b413-4a19-ae6e-bdeb3a3eab30</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Login')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.text-white.ml-auto.waves-effect.waves-themed</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>02c869f9-238b-41e2-b159-20be8f279de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://127.0.0.1:8000/login</value>
      <webElementGuid>98873067-5e5b-432f-bca7-9620524b27a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary text-white ml-auto waves-effect waves-themed</value>
      <webElementGuid>55416901-1a33-4b60-a2ac-98d5ab46fb4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Login
        </value>
      <webElementGuid>c5cd6b39-003b-4cfc-861f-67c7ec3a960a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done desktop chrome webkit&quot;]/div[@class=&quot;page-wrapper auth&quot;]/div[@class=&quot;page-inner bg-brand-gradient&quot;]/div[@class=&quot;page-content-wrapper bg-transparent m-0&quot;]/div[@class=&quot;height-10 w-100 shadow-lg px-4 bg-brand-gradient&quot;]/div[@class=&quot;d-flex align-items-center container p-0&quot;]/a[@class=&quot;btn btn-primary text-white ml-auto waves-effect waves-themed&quot;]</value>
      <webElementGuid>bb60a865-81ad-44ce-9452-a6fc159c5b34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Login')]</value>
      <webElementGuid>1af00c64-b187-42bd-8542-6cf6d94ad5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simikro'])[1]/preceding::a[1]</value>
      <webElementGuid>71b95243-2e5e-4855-831c-3110aaefce87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Login']/parent::*</value>
      <webElementGuid>0368da3a-c6b5-4186-9df6-89e71aff58fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://127.0.0.1:8000/login']</value>
      <webElementGuid>09b728b2-6c47-4963-a31b-8d23b111eb0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a</value>
      <webElementGuid>f62997a9-c668-4503-bfe7-ee340947c325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://127.0.0.1:8000/login' and (text() = '
            Login
        ' or . = '
            Login
        ')]</value>
      <webElementGuid>953dd81f-2b7e-4844-8e78-03bda6fd3fd6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
