<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Keluar</name>
   <tag></tag>
   <elementGuidId>50a782be-9509-4403-b1f5-f33c89e27277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ya-atau-tidak']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ya-atau-tidak</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Keluar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb909789-504b-47a8-9349-4096250a99bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>47229f42-f866-47ff-9df4-7c05545a6963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ya-atau-tidak</value>
      <webElementGuid>b2ee33e3-2f9d-4dc7-bb16-a1ff5f81c8a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item fw-500 pt-3 pb-3</value>
      <webElementGuid>c99b9bf6-1c29-454e-a582-26ac2b7e740c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-title</name>
      <type>Main</type>
      <value>Konfirmasi</value>
      <webElementGuid>adaf8b01-259c-4166-b311-b949e8527677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-message</name>
      <type>Main</type>
      <value>Apakah Anda yakin ingin logout?</value>
      <webElementGuid>f2e8aaee-be71-48d0-97d2-1869060d7802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>e5b87dc7-e629-4094-b21d-b5f067014dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Keluar</value>
      <webElementGuid>72553010-e4eb-4a97-9ead-0246c2d59f41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;pace-done mod-bg-1 mod-nav-link desktop chrome webkit&quot;]/div[@class=&quot;page-wrapper&quot;]/div[@class=&quot;page-inner&quot;]/div[@class=&quot;page-content-wrapper&quot;]/header[@class=&quot;page-header&quot;]/div[@class=&quot;ml-auto d-flex&quot;]/div[@class=&quot;show&quot;]/div[@class=&quot;dropdown-menu dropdown-menu-animated dropdown-lg show&quot;]/form[@id=&quot;logout-form&quot;]/button[@id=&quot;ya-atau-tidak&quot;]</value>
      <webElementGuid>3de42cae-c46d-410d-99a1-a34b6feb4b01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='ya-atau-tidak']</value>
      <webElementGuid>305339fb-72c6-40c6-b114-2b166a408fd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='logout-form']/button</value>
      <webElementGuid>86b0b0e4-bb08-4a7d-ba3b-cc722da44e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='F11'])[1]/following::button[1]</value>
      <webElementGuid>65bfc380-d431-4497-99a6-7e9a9d4613b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fullscreen'])[1]/following::button[1]</value>
      <webElementGuid>d695c20c-1ae2-4b06-818c-15f3cae23e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simikro'])[2]/preceding::button[1]</value>
      <webElementGuid>5a3825a6-e2c8-46a7-bff7-5083f9a62b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dashboard'])[2]/preceding::button[1]</value>
      <webElementGuid>68bc3509-6c77-47d9-a42a-b60b6e9bf0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Keluar']/parent::*</value>
      <webElementGuid>d39e217d-bf10-4794-b5b0-c34bb87c3f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>fbd29f65-3061-437b-93d8-11705533e0dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'ya-atau-tidak' and @title = 'Logout' and (text() = 'Keluar' or . = 'Keluar')]</value>
      <webElementGuid>6db93dc3-de52-4ca2-a7b6-5c37fc52be30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
