<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>em_Pengaturan_fal fa-angle-down</name>
   <tag></tag>
   <elementGuidId>2aca7dce-f0c5-4b2c-90a5-6f0c1930cadc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='js-nav-menu']/li[9]/a/b/em</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>em.fal.fa-angle-down</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Pengaturan &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>8ac88798-9681-4651-a5da-6f86730109ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fal fa-angle-down</value>
      <webElementGuid>494099f4-1287-4924-b756-003ebae51d7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-nav-menu&quot;)/li[9]/a[@class=&quot;waves-effect waves-themed&quot;]/b[@class=&quot;collapse-sign&quot;]/em[@class=&quot;fal fa-angle-down&quot;]</value>
      <webElementGuid>31642b16-c3b5-482e-92c5-acc7b63af4a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='js-nav-menu']/li[9]/a/b/em</value>
      <webElementGuid>cf5f2b5d-5340-4235-a1f0-f90057412eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>ff81b812-ce2c-4a04-b34e-8fc6377d27dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
