<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NILAI REKOMENDASI PROGRAM_nilai_sertifikat</name>
   <tag></tag>
   <elementGuidId>b3bfaae2-c602-4789-abee-6677a948e25b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='nilai_sertifikat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;nilai_sertifikat&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;MASUKKAN NILAI SERTIFIKAT&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0bf8f0ec-defa-4d7d-8b24-8e7e3ddefe0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>71715ea5-2aa7-47df-9410-2277efc121cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nilai_sertifikat</value>
      <webElementGuid>cb92fa26-991c-49f2-8efb-10bb3c49bab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MASUKKAN NILAI SERTIFIKAT</value>
      <webElementGuid>419e91ff-3e02-4d64-bcde-5bfbed2e3683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>bdf1554e-3ff6-4ddb-bfb9-cd83806e43d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-9XJNk&quot;)/div[@class=&quot;panel-container show&quot;]/div[@class=&quot;panel-content&quot;]/div[@class=&quot;row&quot;]/table[@class=&quot;table table-bordered table-hover table-striped w-100&quot;]/tbody[1]/tr[7]/td[2]/input[@class=&quot;form-control&quot;]</value>
      <webElementGuid>a827c5e0-a123-47d4-a515-6ad517d966c5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='nilai_sertifikat']</value>
      <webElementGuid>7c703e60-4d37-453c-b79a-3a34bc89364d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-9XJNk']/div[2]/div/div/table/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>9e841976-8312-4b6c-bcf0-86de6b8d6f9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>62d49308-5a56-417b-bfcd-4d8d816847aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'nilai_sertifikat' and @placeholder = 'MASUKKAN NILAI SERTIFIKAT']</value>
      <webElementGuid>6dc2da5e-3fe2-4cd8-85dd-1cef865258ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
