<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VALID_laprak</name>
   <tag></tag>
   <elementGuidId>06ee4d4e-64ac-4e62-831d-c1301140c5f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='laprak']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;laprak&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;LAPORAN AKHIR VALID TIDAK VALID&quot;i] >> internal:label=&quot;VALID&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d267a8d2-dcb9-460c-8e87-03b229055d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0140f174-b2d3-43df-bbd4-54a3ab4067cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>laprak</value>
      <webElementGuid>97cc3d3a-2158-4c3d-8c52-d6ef4fba6c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>379b53cc-dc8b-442d-9af1-c23335ee36ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-9XJNk&quot;)/div[@class=&quot;panel-container show&quot;]/div[@class=&quot;panel-content&quot;]/div[@class=&quot;row&quot;]/table[@class=&quot;table table-bordered table-hover table-striped w-100&quot;]/tbody[1]/tr[4]/td[2]/label[@class=&quot;text-success&quot;]/input[1]</value>
      <webElementGuid>32b4dc2b-39c6-44db-bf6a-bbb2c349e312</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='laprak']</value>
      <webElementGuid>5256be97-b40e-4651-9b84-279bf6f9a143</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-9XJNk']/div[2]/div/div/table/tbody/tr[4]/td[2]/label/input</value>
      <webElementGuid>eee025cd-2db8-407e-8cb6-6a47c74c1617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>bc098bd9-c91a-43d0-8ea2-ed447e417575</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'laprak']</value>
      <webElementGuid>562cce15-c7bf-4487-9cf5-93f83325c344</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
