<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_TIDAK                                _1c4649</name>
   <tag></tag>
   <elementGuidId>d2cfbcb1-96b0-40dd-abf1-d95283a486e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='nilai_mikroskill']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;nilai_mikroskill&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;TAMPILKAN NILAI TEST MIKROSKILL&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87e6cec3-765b-45dd-840f-e7fe4cecbe7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>88f08061-261a-4efd-9f59-49a08eb5fb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nilai_mikroskill</value>
      <webElementGuid>ba96cba1-1aa4-4c28-a287-732d1995b6a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>TAMPILKAN NILAI TEST MIKROSKILL</value>
      <webElementGuid>011c6d44-3ac9-45e9-9b40-c51799bc6fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>98985f7e-b3bd-4082-bbec-ebc38b331c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c421805a-1ee8-4e5a-a940-975fd3cea9f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control mt-2</value>
      <webElementGuid>99231e12-c1d2-45d5-a692-656dcf680a82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-9XJNk&quot;)/div[@class=&quot;panel-container show&quot;]/div[@class=&quot;panel-content&quot;]/div[@class=&quot;row&quot;]/table[@class=&quot;table table-bordered table-hover table-striped w-100&quot;]/tbody[1]/tr[8]/td[2]/input[@class=&quot;form-control mt-2&quot;]</value>
      <webElementGuid>0acb51b5-de95-4f74-acb2-ad96c4cc87de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='nilai_mikroskill']</value>
      <webElementGuid>503b88f7-62cd-4748-b77e-847c8beb6667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-9XJNk']/div[2]/div/div/table/tbody/tr[8]/td[2]/input</value>
      <webElementGuid>ed056a95-0efd-478f-b72c-01b819c0dc2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/input</value>
      <webElementGuid>085c243b-c043-47f1-8977-1c8d19b95c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'nilai_mikroskill' and @placeholder = 'TAMPILKAN NILAI TEST MIKROSKILL']</value>
      <webElementGuid>9c368ac6-da7f-4423-938d-1786e27e2d31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
