<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VALID_tes_mikroskill</name>
   <tag></tag>
   <elementGuidId>fb2d9f1a-7192-4fd1-ac57-d18c823e8727</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='tes_mikroskill']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;tes_mikroskill&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;NILAI TEST MIKROSKILL VALID TIDAK VALID&quot;i] >> internal:label=&quot;VALID&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ae2ae77-4e56-4d2b-b66b-aa54b7fa29e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>34697aeb-d3da-4fb3-a059-595cbfe122f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>tes_mikroskill</value>
      <webElementGuid>1828e565-8d96-4e19-9606-c1e0580bcb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5d27ea12-7b8a-4ebf-b90d-add9c1164690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-9XJNk&quot;)/div[@class=&quot;panel-container show&quot;]/div[@class=&quot;panel-content&quot;]/div[@class=&quot;row&quot;]/table[@class=&quot;table table-bordered table-hover table-striped w-100&quot;]/tbody[1]/tr[8]/td[2]/label[@class=&quot;text-success&quot;]/input[1]</value>
      <webElementGuid>5a8f3091-bdf3-499b-9954-9e60fd7cd8b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='tes_mikroskill']</value>
      <webElementGuid>20d88684-3a43-40c8-81ad-cd6d10324910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-9XJNk']/div[2]/div/div/table/tbody/tr[8]/td[2]/label/input</value>
      <webElementGuid>2720ddf2-a8de-42b1-b0d4-cd5046760ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/label/input</value>
      <webElementGuid>387793ed-223b-4654-8cb1-5a3837c8d911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'tes_mikroskill']</value>
      <webElementGuid>83bab1ae-3a33-4ae9-b12b-4c744225cd26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
