<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Silahkan tes terlebih dahulu</name>
   <tag></tag>
   <elementGuidId>a9cde239-4e26-48b6-a6c4-e949316893e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='dt-basic-example']/tbody/tr/td[8]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.text-danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Silahkan tes terlebih dahulu&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d64b2c6-3a74-4182-8c93-b82151d8d3c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>1cc7bc83-b4c3-48d6-8a86-7405dfff5d59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Silahkan tes terlebih dahulu</value>
      <webElementGuid>b569db43-b375-4ba7-bfc7-ba2704e10bbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dt-basic-example&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[8]/span[@class=&quot;text-danger&quot;]</value>
      <webElementGuid>e3d220fe-ffd7-47fb-8a61-44b55a9675b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='dt-basic-example']/tbody/tr/td[8]/span</value>
      <webElementGuid>142d8fbe-0919-412e-8a70-bb87670b8cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Belum Test'])[1]/following::span[1]</value>
      <webElementGuid>c1465105-6a51-4d4a-91f7-60e50e4884b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Menunggu Validasi'])[1]/following::span[1]</value>
      <webElementGuid>ab8d6020-9e11-4ec9-bf45-5cc269d4f48d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rincian'])[1]/preceding::span[1]</value>
      <webElementGuid>168d9c97-6c3b-4076-882c-787e7a2e9223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tes Mikroskill'])[1]/preceding::span[1]</value>
      <webElementGuid>7e0d4cab-832a-4ef1-acd1-4bd32cddbeef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Silahkan tes terlebih dahulu']/parent::*</value>
      <webElementGuid>34a1243f-1402-4765-86cf-653f05d286c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/span</value>
      <webElementGuid>ee92f830-9959-40ba-98fd-c47e506f7e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Silahkan tes terlebih dahulu' or . = 'Silahkan tes terlebih dahulu')]</value>
      <webElementGuid>07330952-327f-4e4a-b64e-01e7fec54d43</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
