<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Pengaturan</name>
   <tag></tag>
   <elementGuidId>610fec92-412e-4d70-a9a8-1a2230e8ae86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Pengaturan' or . = 'Pengaturan')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(5) > a.waves-effect.waves-themed > span.nav-link-text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Pengaturan' or . = 'Pengaturan')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot; Pengaturan &quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b15d15cf-cbcf-414b-ac1d-068e7d68f40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link-text</value>
      <webElementGuid>21d07081-91aa-4186-a95a-fc5d087c76b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-i18n</name>
      <type>Main</type>
      <value>nav.settings</value>
      <webElementGuid>5a434573-d960-4a6c-ae8e-1fe1900bd89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Pengaturan</value>
      <webElementGuid>86e891af-a019-4fa7-be54-44ad8d69c85f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-nav-menu&quot;)/li[5]/a[@class=&quot;waves-effect waves-themed&quot;]/span[@class=&quot;nav-link-text&quot;]</value>
      <webElementGuid>ab99f467-b1f6-4ca4-9cff-d48f382b2146</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='js-nav-menu']/li[5]/a/span</value>
      <webElementGuid>4efec8fd-4376-43f2-9d90-33f7a365a288</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan'])[1]/following::span[1]</value>
      <webElementGuid>a889ecfa-4ae5-4a67-a9a0-52a033af4a3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengajuan Konversi'])[1]/following::span[1]</value>
      <webElementGuid>96d5497a-7743-4591-b48d-d4ceea415c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Profil Pengguna'])[1]/preceding::span[1]</value>
      <webElementGuid>5138d434-7073-4a9e-8f00-de0d9b5f220f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tentang Simikro'])[1]/preceding::span[2]</value>
      <webElementGuid>cf2b03be-f87b-4246-ba05-c0049dd0aa31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/span</value>
      <webElementGuid>290d176f-8d87-46ea-a3b7-0e69c912b101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Pengaturan' or . = 'Pengaturan')]</value>
      <webElementGuid>8176bfc3-0814-4beb-8b60-c6ea8bc8789c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
