<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_KOMENTAR_feedback</name>
   <tag></tag>
   <elementGuidId>3b498e74-ed4f-4e51-bba2-adfb9fa5dc94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name='feedback']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;feedback&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;MASUKKAN KOMENTAR DISINI&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>4f887e48-4a9e-4a8a-8bfd-8d7e5c18afd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>feedback</value>
      <webElementGuid>c87fd075-a4ba-443e-b78a-179ff24bbdb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>91cc49dc-f85e-42c7-949a-76d25a1fee9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>14ecacdb-d4b2-4aa7-a127-51ad0cf82c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>MASUKKAN KOMENTAR DISINI</value>
      <webElementGuid>64a73bbf-462e-4d61-85ab-4eedb82211da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;panel-9XJNk&quot;)/div[@class=&quot;panel-container show&quot;]/div[@class=&quot;panel-content&quot;]/div[@class=&quot;row&quot;]/table[@class=&quot;table table-bordered table-hover table-striped w-100&quot;]/tbody[1]/tr[10]/td[2]/textarea[@class=&quot;form-control&quot;]</value>
      <webElementGuid>4b994474-be73-48e5-b216-d4ff742a2c9c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='feedback']</value>
      <webElementGuid>55df15d4-04ad-4c8d-9228-2c8659e1dc32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='panel-9XJNk']/div[2]/div/div/table/tbody/tr[10]/td[2]/textarea</value>
      <webElementGuid>19fa12f9-e19e-4f24-9eda-6b5938c5b0ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>08e348de-9464-4e0d-8542-f9a909d3a044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'feedback' and @placeholder = 'MASUKKAN KOMENTAR DISINI']</value>
      <webElementGuid>887e7435-7ee6-4265-ad3c-8cc9b3e10ad0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
